import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  console.log(session)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='navbar'>
          <Link href="/" className="logo">Sunrise 블로그</Link>
          <Link href="/list">글목록</Link>
          <Link href="/write">글쓰기</Link>
          {session?.user ? (
            <>
              <LogoutBtn/>
              <img src={session?.user?.image} className="avatar"/>
              <h3 className='email'>{session?.user?.email}</h3>
            </>
          ) : <LoginBtn/>}
          
        </div>
        {children}
      </body>
    </html>
  )
}
